# .github/workflows/gradle-build-pr.yml
# https://github.com/marketplace/actions/gradle-command
name: sample-android
on:
  push:
    branches:
      - main
    paths:
      - 'sample-android/**'
      - '!**.md'
      - '!**.adoc'
      - '!.editorconfig'
      - '!**/.gitignore'
  workflow_dispatch:
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: plugins
          build-root-directory: plugins
          arguments: check publishToMavenLocal --stacktrace
      - uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: plugins
          build-root-directory: sample-android
          arguments: refreshVersions --stacktrace
      - uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: plugins
          build-root-directory: sample-android
          arguments: check --stacktrace
